FROM httpd:2.4
COPY ./src/api /usr/local/apache2/htdocs/api
COPY ./src/assets /usr/local/apache2/htdocs/assets
COPY ./src/config /usr/local/apache2/htdocs/config
COPY ./src/css /usr/local/apache2/htdocs/css
COPY ./src/js /usr/local/apache2/htdocs/js
COPY ./src/pages /usr/local/apache2/htdocs/pages
COPY ./src/services /usr/local/apache2/htdocs/services
COPY ./src/utils /usr/local/apache2/htdocs/utils
COPY  ./src/index.html /usr/local/apache2/htdocs/index.html
